# DO NOT REMOVE THIS
theme = "harbor"

baseURL = "https://utsavgupta.in/"
title = "Utsav Gupta"
author = "Utsav Gupta"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[Author]
  name = "Utsav Gupta"

[permalinks]
	post = "/blog/:slug/"
	page = "/:filename/"

[outputs]
    section = ["JSON", "HTML"]

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "tags"
  weight = 3

[params]
  mainSections = ["post"]
  favicon16 = "favicon-16x16.png"
  favicon32 = "favicon-32x32.png"
  description = "Personal website and blog of yet another software developer"
  css = ["css/custom.css"]

[params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[params.social]
  github = "utsavgupta"
  linkedin = "utsav-gupta"
  stackoverflow = "https://stackoverflow.com/users/520209/utsav"
  email = "mail@utsavgupta.in"
  publickey = "public_key.txt"

[markup.goldmark.renderer] 
  unsafe= true 